name: cavs_smart_store
description: Smart Mini Store CAVS - Flutter + Firebase demo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.8.0
  cloud_firestore: ^4.7.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.0.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.5
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
